const types = {
  AUTH_CHECK_REQUEST: 'AUTH_CHECK_REQUEST',
  AUTH_CHECK_RECEIVE: 'AUTH_CHECK_RECEIVE',
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_RECEIVE: 'AUTH_RECEIVE',
  AUTH_REMOVE: 'AUTH_REMOVE',
  ALBUM_LIST_REQUEST: 'ALBUM_LIST_REQUEST',
  ALBUM_LIST_RECEIVE: 'ALBUM_LIST_RECEIVE',
  USER_PROFILE_REQUEST: 'USER_PROFILE_REQUEST',
  USER_PROFILE_RECEIVE: 'USER_PROFILE_RECEIVE',
  PHOTO_LIST_REQUEST: 'PHOTO_LIST_REQUEST',
  PHOTO_LIST_RECEIVE: 'PHOTO_LIST_RECEIVE',
};
export default types;
